language: go
go:
- 1.11.x
jobs:
  include:
  - stage: Tests
    script:
    - make test
    - make build
  - stage: Deploy Staging
    if: branch = master
    before_deploy:
    - npm install -g serverless
    - npm install --save-dev serverless-domain-manager
    - npm install --save-dev serverless-plugin-tracing
    deploy:
      skip_cleanup: true
      provider: script
      script: make stage
      on:
        branch: master
  - stage: Deploy Release
    if: tag IS present
    before_deploy:
    - npm install -g serverless
    - npm install serverless-domain-manager --save-dev
    deploy:
      - provider: releases
        skip_cleanup: true
        api_key: ${GITHUB_TOKEN}
        file:
          - "bin/*"
          - "templates/*"
          - "img/*"
          - "serverless_stages.yml"
          - "serverless.yml"
        on:
          tags: true
          repo: billglover/bbot
      - provider: script
        skip_cleanup: true
        script: make release
        on:
          tags: true
          repo: billglover/bbot
