language: go

go:
  - "1.11.x"

jobs:
  include:
    - stage: "Tests"
      script:
        - make test
        - make build

    - stage: "Deploy Staging"
      before_deploy:
        - npm install -g serverless
        - npm install -g serverless-domain-manager
      deploy:
        skip_cleanup: true
        provider: script
        script: make stage
        on:
          all_branches: true

    - stage: "Deploy Release"
      before_deploy:
        - npm install -g serverless
        - npm install -g serverless-domain-manager
      deploy:
        skip_cleanup: true
        provider: script
        script: make release
        on:
          tags: true
          branch: master